version: '3'
services:
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/mysql:8.0 # 原镜像`mysql:8.0`
    container_name: mysql8.0 # 容器名为'mysql8.0'
    restart: unless-stopped # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:
      # 数据卷挂载路径设置,将本机目录映射到容器目录
      #- "./mysql8.0/my.cnf:/etc/mysql/my.cnf"
      - "./data:/var/lib/mysql"
      #      - "./mysql8.0/conf.d:/etc/mysql/conf.d"
      #- "./mysql8.0/mysql-files:/var/lib/mysql-files"
    environment:
      # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: 1234 # 设置root用户密码
      MYSQL_DATABASE: feizai # 初始化的数据库名称
    ports:
      # 映射端口
      - "3306:3306"
  express:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./public:./public
    ports:
      - "3000:3000"
